### ISSUE TITLE
Where did you get the data download

### ISSUE THREAD

**Issue by coreym** [jhajagos/ny_sparcs_import#1]
Hi, I noticed you were able to get a very comprehensive file for import, were you able to get this all in one file? 

The .csv downloads available here: https://www.healthdata.gov/data/dataset/hospital-inpatient-discharges-sparcs-de-identified-2012 and on the health.data.ny.gov site both have a much smaller number of fields - around 38.

**Comment by jhajagos** [comment]
You can get the limited data sets by applying for access

https://www.health.ny.gov/statistics/sparcs/access/

It comes in either a single text or multiple text files that need to be converted into CSV.  Most of the code that I am sharing is for the conversion process. 

-Janos

**Comment by coreym** [comment]
Thank you! It looks like the publicly available data is a very small subset
